### PR TITLE
Themes

### PR DESCRIPTION
**Pull request by jerodsanto**
First steps toward theme support. Things left to do:

- [x] implement day theme
- [x] refine night theme from community feedback
- [x] swap logo based on Theme setting
- [x] add custom field to Nightly CM group
- [ ] test via the Nightly Test CM group
- [x] tweak copy on link in footer
- [x] decide if we want to add a temporary message in header/footer
- [ ] update screenshots on GH readme, subscribe page, GH Archive (?)

### CODE REVIEW

**Comment by jerodsanto** [comment]
@adamstac tag, you're it. Let me know if you have any questions. Easiest way to dev this out is to just toggle the theme css link on the web version.

**Comment by adamstac** [comment]
Ok, @jerodsanto. Shipped the updates to the night and day themes. I just need your help on the best way to swap the logo based on the theme.

**Comment by zeke** [comment]
The light theme looks great. Thanks!

**Comment by jerodsanto** [comment]
@zeke glad you like it! :beers:

**Pull request merged**
